In [1]:
import torch

In [2]:
torch.__version__

'2.7.1+cu128'

In [3]:
a = torch.ones(3, 3)
a

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [4]:
b = torch.ones(3, 3)

In [5]:
a + b

tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])

查看有没有显卡，有没有激活

In [6]:
torch.cuda.is_available()

True

In [7]:
a = a.to('cuda')
b = b.to('cuda')
a + b

tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]], device='cuda:0')