Q1: create a tensor `a` from `list(range(9))`. Predict and then check the size, offset, and stride.

In [1]:
import torch

In [3]:
a = torch.tensor(list(range(9)))
a

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [4]:
a.size(), a.storage_offset(), a.stride()

(torch.Size([9]), 0, (1,))

a: Create a new tensor using `b = a.view(3, 3)`. When does `view` do? Check that `a` and `b` share the same storage.

In [6]:
b = a.view(3, 3)
b

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [7]:
b.storage()

C:\Users\31987\AppData\Local\Temp\ipykernel_26112\1362296067.py:1: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  b.storage()


 0
 1
 2
 3
 4
 5
 6
 7
 8
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 9]

In [21]:
id(a.storage()), id(b.storage())

(2405200894896, 2405200894896)

In [34]:
id(a.storage()) == id(b.storage())

True

有时一样，有时不一样

b: Create a tensor `c = b[1:,1:]`. Predict and then check the size, offset, and stride.

In [35]:
c = b[1:,1:]
c

tensor([[4, 5],
        [7, 8]])

In [37]:
c.storage()

 0
 1
 2
 3
 4
 5
 6
 7
 8
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 9]

In [36]:
c.size(), c.storage_offset(), c.stride()

(torch.Size([2, 2]), 4, (3, 1))

Q2: Pick a mathematical operation like cosine or square root. Can you find a corresponding function in the torch library?

In [38]:
a = a.to(float)

In [39]:
torch.cos(a)

tensor([ 1.0000,  0.5403, -0.4161, -0.9900, -0.6536,  0.2837,  0.9602,  0.7539,
        -0.1455], dtype=torch.float64)

In [40]:
torch.sqrt(a)

tensor([0.0000, 1.0000, 1.4142, 1.7321, 2.0000, 2.2361, 2.4495, 2.6458, 2.8284],
       dtype=torch.float64)