In [40]:
import torch

In [41]:
a = torch.ones(3)
a

tensor([1., 1., 1.])

In [42]:
a[2]

tensor(1.)

In [43]:
float(a[1])

1.0

In [44]:
points = torch.Tensor([4, 1, 5, 3, 2, 1])
points

tensor([4., 1., 5., 3., 2., 1.])

In [45]:
points = points.reshape(3, 2)
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [46]:
points[0, 0]

tensor(4.)

In [47]:
points[0][0]

tensor(4.)

In [48]:
(points.storage())

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [49]:
second_point = points[1]
second_point

tensor([5., 3.])

In [50]:
second_point.storage_offset()

2

In [51]:
second_point.size()

torch.Size([2])

In [52]:
id(second_point)

2510140911568

In [53]:
id(points[1])

2510140112352

In [54]:
another_point = points[1].clone()
id(another_point)

2510140924672

In [55]:
another_point

tensor([5., 3.])

In [56]:
points.stride()

(2, 1)

points 3行2列

按照storage里的顺序

在维度0内跳转，每行跳2个元素

在维度1内，每次跳1个元素

In [57]:
points_t = points.t()
points_t

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [59]:
id(points)

2510140106512

In [58]:
id(points_t)

2510140026592

In [60]:
points_t.storage()

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [61]:
points_t.stride()

(1, 2)

In [62]:
some_t = torch.ones(3, 4, 5)
some_t.stride()

(20, 5, 1)

In [63]:
transpose_t = some_t.transpose(0, 2)
transpose_t.size()

torch.Size([5, 4, 3])

In [64]:
transpose_t.stride()

(1, 5, 20)

是否按内存中顺序

In [65]:
points_t.is_contiguous()

False

In [66]:
points.is_contiguous()

True