In [1]:
import torch

In [2]:
some_list = list(range(6))
some_list

[0, 1, 2, 3, 4, 5]

In [3]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [4]:
points[1:]

tensor([[5., 3.],
        [2., 1.]])

In [5]:
points[1:,1]

tensor([3., 1.])

In [6]:
points[None]

tensor([[[4., 1.],
         [5., 3.],
         [2., 1.]]])

In [7]:
points = torch.ones(3, 4)
points_np = points.numpy()
points_np

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [37]:
points = torch.from_numpy(points_np)
points

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [9]:
torch.save(points, '../../data/p1ch3/ourpoints.t')

write binary

In [10]:
with open('../../data/p1ch3/ourpoints.t', 'wb') as f:
    torch.save(points, f)

In [11]:
a = torch.load('../../data/p1ch3/ourpoints.t')
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [12]:
with open('../../data/p1ch3/ourpoints.t', 'rb') as f:
    a = torch.load(f)

a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [13]:
import h5py

In [14]:
f = h5py.File('../../data/p1ch3/ourpoints.hdf5', 'w')
dset = f.create_dataset('coords', data=points.numpy())
f.close()

In [25]:
f = h5py.File('../../data/p1ch3/ourpoints.hdf5', 'r')
dset = f['coords']
dset

<HDF5 dataset "coords": shape (3, 4), type "<f4">

In [26]:
last_points = dset[-2:]
last_points

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [27]:
points = torch.from_numpy(last_points)
f.close()
points

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [38]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])

In [36]:
points_gpu = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]], device='cuda')

In [39]:
points = points.to('cuda')

In [41]:
points + points_gpu

tensor([[ 8.,  2.],
        [10.,  6.],
        [ 4.,  2.]], device='cuda:0')