In [1]:
import torch

In [2]:
double_points = torch.ones(10, 2, dtype=torch.double)

short_points = torch.tensor([[1, 2], [3, 4]], dtype=torch.short)

In [3]:
double_points.dtype, short_points.dtype

(torch.float64, torch.int16)

In [4]:
double_points = torch.zeros(10, 2).double()

short_points = torch.ones(10, 2).short()

In [5]:
double_points.dtype, short_points.dtype

(torch.float64, torch.int16)

In [6]:
double_points = torch.zeros(10, 2).to(torch.double)

short_points = torch.ones(10, 2).to(torch.short)

In [7]:
double_points.dtype, short_points.dtype

(torch.float64, torch.int16)

In [9]:
points_64 = torch.rand(5, dtype=torch.double)
points_64

tensor([0.3949, 0.3217, 0.9123, 0.9806, 0.9197], dtype=torch.float64)

In [11]:
points_short = points_64.to(torch.short)
points_short

tensor([0, 0, 0, 0, 0], dtype=torch.int16)

只取整数部分

In [12]:
points_64 * points_short

tensor([0., 0., 0., 0., 0.], dtype=torch.float64)